name: Push

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - chrome
          - firefox
          - edge
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      # - name: Build
      #   run: bun run build
      - name: Build and Zip
        run: bun run zip:${{ matrix.target }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pageassist-${{ matrix.target }}
          path: |
            build/*${{ matrix.target }}.zip
            build/*sources.zip
          if-no-files-found: error
